### ISSUE TITLE
feat: 테스트 결과 페이지 UI 작업

### ISSUE THREAD

**Issue by useonglee** [jeju-power-test/frontend#10]
### ISSUE
- Type: feature

### TODO
1. [x] 카드 컴포넌트 UI 작업
2. [x] 결과 페이지 UI 작업
3. [x] 결과 페이지 목업 데이터
