### ISSUE TITLE
feat: quiz 페이지 QA 이슈 수정

### ISSUE THREAD

**Issue by useonglee** [jeju-power-test/frontend#30]
### ISSUE
- Type: feature

### TODO
1. [x] quiz 페이지 뒤로갔을 경우 progressbar 오류 수정
2. [x] 문제에 이미지 넣기
3. [x] 문제 word-break 넣기
4. [x] 레이아웃 상단으로 고정
5. [x] 프로그레스바 아이콘 UI 위치 수정
6. [x] 퀴즈 페이지에서 새로고침 시 첫 페이지로 이동
